name:                Grapha
version:             0.1.0.0
github:              "ghlin/Grapha"
license:             BSD3
author:              "ghlin"
maintainer:          "2012.2.9.ghl@gmail.com"
copyright:           "2019 ghlin"

extra-source-files:
- README.md

description:         A functional programming language.

dependencies:
- base >= 4.7 && < 5
- text
- transformers
- containers
- megaparsec
- parser-combinators
- prettyprinter
- pretty-simple
- raw-strings-qq

library:
  source-dirs: src

executables:
  grc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Grapha

tests:
  Grapha-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Grapha
